#!/bin/bash

function errorOut {
    echo "ERROR: $1"
    exit 1
}

JWT_VAL="$1"

[ -z "$JWT_VAL" ] && errorOut "No JWT specified"

curl -s -H "Content-type: application/json" -d "{ \"jwt\" : \"$JWT_VAL\"}" -X POST http://127.0.0.1:4321/session/end | jq '.'

exit 0
